language: node_js
matrix:
  include:
    - os: linux
      node_js: stable
    - os: linux
      node_js: 8.9
    - os: windows
      node_js: stable
    - os: windows
      node_js: 8.9

script:
  - npm test

services:
  - mongodb
  - redis-server
